//Prints odd integers through 13 and 27 (one on each line) using a for loop

#include <stdio.h>

int main () {

    /*Define a for loop with parameters of i going from 13 to 27
     *i goes up by 2 until reaches 27
     */
    for(int i=13; i<=27; i=i+2){
       
        //Print the values generated by the for loop, one on each line
        printf("%i\n",i);
        }

    return 0;
}
